;;; kubed-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from cobra.el

(autoload 'cobra-read-command-line "cobra" "\
Prompt with PROMPT for a command line starting with INITIAL.

Optional argument HIST is the name of the history list variable to use,
if it is nil or omitted, it defaults to `shell-command-history'.

(fn PROMPT INITIAL &optional HIST)")
(register-definition-prefixes "cobra" '("cobra-"))


;;; Generated autoloads from kubed.el

(autoload 'kubed-display-resource "kubed" "\
Display Kubernetes RESOURCE of type TYPE in CONTEXT.

For namespaced resource types, NAMESPACE is the namespace of RESOURCE.

Interactively, use the current context and namespace by default, and
prompt for TYPE and RESOURCE.  With a prefix argument \\[universal-argument],
prompt for NAMESPACE.  With a double prefix argument \\[universal-argument] \\[universal-argument],
prompt for CONTEXT as well.

(fn TYPE RESOURCE CONTEXT &optional NAMESPACE)" t)
(autoload 'kubed-display-resource-handle-bookmark "kubed" "\
Display Kubernetes resource according to BOOKMARK.

(fn BOOKMARK)")
(autoload 'kubed-list-handle-bookmark "kubed" "\
Display Kubernetes resource according to BOOKMARK.

(fn BOOKMARK)")
(autoload 'kubed-delete-resources "kubed" "\
Delete Kubernetes RESOURCES of type TYPE in context CONTEXT.

For namespaced resource types, NAMESPACE is the namespace of RESOURCE.

Interactively, use the current context and namespace by default, and
prompt for TYPE and RESOURCES.  With a prefix argument \\[universal-argument],
prompt for NAMESPACE.  With a double prefix argument \\[universal-argument] \\[universal-argument],
prompt for CONTEXT as well.

(fn TYPE RESOURCES CONTEXT &optional NAMESPACE)" t)
(autoload 'kubed-edit-resource "kubed" "\
Edit Kubernetes RESOURCE of type TYPE in context CONTEXT.

For namespaced resource types, NAMESPACE is the namespace of RESOURCE.

Interactively, use the current context and namespace by default, and
prompt for TYPE and RESOURCES.  With a prefix argument \\[universal-argument],
prompt for NAMESPACE.  With a double prefix argument \\[universal-argument] \\[universal-argument],
prompt for CONTEXT as well.

(fn TYPE RESOURCE CONTEXT &optional NAMESPACE)" t)
(autoload 'kubed-define-resource "kubed" "\
Define Kubernetes RESOURCE with associated PROPERTIES and COMMANDS.

RESOURCE is a symbol corresponding to a Kubernetes resource type, such
as `pod' or `service'.  This macro defines the following commands for
interacting with Kubernetes RESOURCEs:

- `kubed-display-RESOURCE': prompt for a RESOURCE and display its
  description in YAML format.  See also `kubed-yaml-setup-hook'.
- `kubed-edit-RESOURCE': prompt for a RESOURCE and edit it.
- `kubed-delete-RESOURCE': prompt for a RESOURCE and delete it.
- `kubed-list-RESOURCEs': display a buffer listing all RESOURCEs in the
  current namespace.  The RESOURCEs list buffer uses a dedicated major
  mode, `kubed-RESOURCEs-mode', which is also defined by this macro.
- `kubed-create-RESOURCE': create a RESOURCE from a YAML or a JSON file.
- `kubed-explain-RESOURCEs': show buffer with help about RESOURCEs.

This macro also defines a prefix keymap, `kubed-RESOURCE-prefix-map',
with bindings for the above commands.

PROPERTIES is a list of lists (PROP JSON-PATH WIDTH SORT FORMAT . ATTRS)
that specify properties of RESOURCEs.  PROP is the name of the property,
as a symbol; JSON-PATH is a JSONPath expression that evaluates to the
value of PROP when applied to the JSON representation of a RESOURCE.
WIDTH, SORT, FORMAT and ATTRS are optional and can be omitted.  WIDTH is
used as the default width of the column corresponding to PROP in
RESOURCEs list buffers; SORT is sort predicate, a function that takes
two values of PROP as strings and returns non-nil if the first should
sort before the second; FORMAT is a function that takes a value of PROP
and formats it.  If you provide a FORMAT function and a SORT function,
then the SORT function gets the formatted values (the output of the
FORMAT function), not the original values.  If you want to sort based on
the unformatted original values, you can store them as text properties
in your FORMAT function and access them in your SORT function.

ATTRS is a plist of additional attributes of the PROP column, see
`tabulated-list-format' for available attributes.

For example, if PROPERTIES is (phase \".status.phase\" 10) that means
that RESOURCE has a `phase' property at JSONPath \".status.phase\" whose
values are typically 10 columns wide.  The first property in PROPERTIES
is used to annotate completion candidates when prompting for a RESOURCE.

COMMANDS is a list of elements (COMMAND KEYS DOC-PREFIX . BODY) that
define commands for RESOURCE list buffers.  COMMAND is a symbol
specifying the suffix of the command name, the full name of the command
is `kubed-RESOURCEs-COMMAND' (for example, `kubed-pods-shell'); KEYS is
either a string that specifies a key sequence to bind to the command in
`kubed-RESOURCEs-mode-map', or nil if the command should not be bound;
DOC-PREFIX is a string used to construct the docstring of the command,
this macro appends the string \" Kubernetes RESOURCE at point.\" to it
to obtain the final docstring; lastly, BODY is the body the command.
Within BODY, the variable RESOURCE is let-bound to the name of the
RESOURCE at point.  For example, if RESOURCE is `pod', the following
COMMANDS element defines a command `kubed-pods-frob' and binds it to the
key \"f\" in `kubed-pods-mode-map':

  (frob \"f\" \"Frobnicate\"
        (message \"Preparing...\")
        (frobnicate-pod pod)
        (message \"Done.\"))

By default, this macro assumes that RESOURCE is namespaced.  To define a
namespaceless resource type, put `:namespaced nil' before COMMANDS:

  (kubed-define-resource global-thingy (PROP1 PROP2 ...) :namespaced nil
    CMD1
    CMD2
    ...)

Other keyword arguments that go between PROPERTIES and COMMANDS are:

- `:create (ARGLIST DOCSTRING INTERACTIVE BODY...)': specialize the
  resource creation command, `kubed-create-RESOURCE'.  ARGLIST,
  DOCSTRING, INTERACTIVE and BODY have the same meaning as in `defun'.
- `:prefix ((KEY LABEL DEFINITION)...)': additional keybinding for the
  prefix keymap `kubed-RESOURCE-prefix-map' and the
  `kubed-RESOURCE-menu-map' menu.  Each element (KEY LABEL DEFINITION)
  says to bind KEY to DEFINITION in `kubed-RESOURCE-menu-map', and to
  add DEFINITION to `kubed-RESOURCE-menu-map' with the label LABEL.
- `:plural PLURAL': specify plural form of RESOURCE, as a symbol.  If
  you omit this keyword argument, the plural form defaults to RESOURCE
  followed by \"s\".
- `:logs t': generate `kubed-logs-for-RESOURCE' command.
- `:suffixes (SUFFIX...)': add type-specific transient suffixes to
  `kubed-list-transient'.

(fn RESOURCE &optional PROPERTIES &rest COMMANDS)" nil t)
(function-put 'kubed-define-resource 'lisp-indent-function 2)
 (autoload 'kubed-display-pod "kubed" nil t)
 (autoload 'kubed-edit-pod "kubed" nil t)
 (autoload 'kubed-delete-pods "kubed" nil t)
 (autoload 'kubed-list-pods "kubed" nil t)
 (autoload 'kubed-create-pod "kubed" nil t)
 (autoload 'kubed-logs-for-pod "kubed" nil t)
 (autoload 'kubed-pod-prefix-map "kubed" nil t 'keymap)
 (autoload 'kubed-display-namespace "kubed" nil t)
 (autoload 'kubed-edit-namespace "kubed" nil t)
 (autoload 'kubed-delete-namespaces "kubed" nil t)
 (autoload 'kubed-list-namespaces "kubed" nil t)
 (autoload 'kubed-create-namespace "kubed" nil t)
 (autoload 'kubed-namespace-prefix-map "kubed" nil t 'keymap)
 (autoload 'kubed-display-persistentvolume "kubed" nil t)
 (autoload 'kubed-edit-persistentvolume "kubed" nil t)
 (autoload 'kubed-delete-persistentvolumes "kubed" nil t)
 (autoload 'kubed-list-persistentvolumes "kubed" nil t)
 (autoload 'kubed-create-persistentvolume "kubed" nil t)
 (autoload 'kubed-persistentvolume-prefix-map "kubed" nil t 'keymap)
 (autoload 'kubed-display-service "kubed" nil t)
 (autoload 'kubed-edit-service "kubed" nil t)
 (autoload 'kubed-delete-services "kubed" nil t)
 (autoload 'kubed-list-services "kubed" nil t)
 (autoload 'kubed-create-service "kubed" nil t)
 (autoload 'kubed-logs-for-service "kubed" nil t)
 (autoload 'kubed-service-prefix-map "kubed" nil t 'keymap)
 (autoload 'kubed-display-secret "kubed" nil t)
 (autoload 'kubed-edit-secret "kubed" nil t)
 (autoload 'kubed-delete-secrets "kubed" nil t)
 (autoload 'kubed-list-secrets "kubed" nil t)
 (autoload 'kubed-create-secret "kubed" nil t)
 (autoload 'kubed-secret-prefix-map "kubed" nil t 'keymap)
 (autoload 'kubed-display-job "kubed" nil t)
 (autoload 'kubed-edit-job "kubed" nil t)
 (autoload 'kubed-delete-jobs "kubed" nil t)
 (autoload 'kubed-list-jobs "kubed" nil t)
 (autoload 'kubed-create-job "kubed" nil t)
 (autoload 'kubed-logs-for-job "kubed" nil t)
 (autoload 'kubed-job-prefix-map "kubed" nil t 'keymap)
(autoload 'kubed-watch-deployment-status "kubed" "\
Show and update status of Kubernetes deployment DEP in a dedicate buffer.

Optional argument CONTEXT is the `kubectl' context to use, defaulting to
the current context; NAMESPACE is the namespace of DEP, defaulting to
the current namespace.  CB is an optional callback function to call with
no arguments when the deployment ends.

Interactively, prompt for DEP.  With a prefix argument, prompt for
NAMESPACE too.  With a double prefix argument, also prompt for CONTEXT.

(fn DEP &optional CONTEXT NAMESPACE CB)" t)
(autoload 'kubed-scale-deployment "kubed" "\
Scale deployment DEP in namespace NAMESPACE via CONTEXT to REPS replicas.

Optional argument CONTEXT is the `kubectl' context to use, defaulting to
the current context; NAMESPACE is the namespace of DEP, defaulting to
the current namespace.

Interactively, prompt for DEP.  With a prefix argument, prompt for
NAMESPACE too.  With a double prefix argument, also prompt for CONTEXT.

(fn DEP REPS &optional CONTEXT NAMESPACE)" t)
(autoload 'kubed-restart-deployment "kubed" "\
Restart Kubernetes deployment DEP in namespace NAMESPACE via CONTEXT.

Optional argument CONTEXT is the `kubectl' context to use, defaulting to
the current context; NAMESPACE is the namespace of DEP, defaulting to
the current namespace.  CB is an optional callback function to call with
no arguments when the deployment ends.

Interactively, prompt for DEP.  With a prefix argument, prompt for
NAMESPACE too.  With a double prefix argument, also prompt for CONTEXT.

(fn DEP &optional CONTEXT NAMESPACE)" t)
 (autoload 'kubed-display-deployment "kubed" nil t)
 (autoload 'kubed-edit-deployment "kubed" nil t)
 (autoload 'kubed-delete-deployments "kubed" nil t)
 (autoload 'kubed-list-deployments "kubed" nil t)
 (autoload 'kubed-create-deployment "kubed" nil t)
 (autoload 'kubed-logs-for-deployment "kubed" nil t)
 (autoload 'kubed-deployment-prefix-map "kubed" nil t 'keymap)
 (autoload 'kubed-display-replicaset "kubed" nil t)
 (autoload 'kubed-edit-replicaset "kubed" nil t)
 (autoload 'kubed-delete-replicasets "kubed" nil t)
 (autoload 'kubed-list-replicasets "kubed" nil t)
 (autoload 'kubed-create-replicaset "kubed" nil t)
 (autoload 'kubed-logs-for-replicaset "kubed" nil t)
 (autoload 'kubed-replicaset-prefix-map "kubed" nil t 'keymap)
 (autoload 'kubed-display-daemonset "kubed" nil t)
 (autoload 'kubed-edit-daemonset "kubed" nil t)
 (autoload 'kubed-delete-daemonsets "kubed" nil t)
 (autoload 'kubed-list-daemonsets "kubed" nil t)
 (autoload 'kubed-create-daemonset "kubed" nil t)
 (autoload 'kubed-logs-for-daemonset "kubed" nil t)
 (autoload 'kubed-daemonset-prefix-map "kubed" nil t 'keymap)
 (autoload 'kubed-display-statefulset "kubed" nil t)
 (autoload 'kubed-edit-statefulset "kubed" nil t)
 (autoload 'kubed-delete-statefulsets "kubed" nil t)
 (autoload 'kubed-list-statefulsets "kubed" nil t)
 (autoload 'kubed-create-statefulset "kubed" nil t)
 (autoload 'kubed-logs-for-statefulset "kubed" nil t)
 (autoload 'kubed-statefulset-prefix-map "kubed" nil t 'keymap)
 (autoload 'kubed-display-cronjob "kubed" nil t)
 (autoload 'kubed-edit-cronjob "kubed" nil t)
 (autoload 'kubed-delete-cronjobs "kubed" nil t)
 (autoload 'kubed-list-cronjobs "kubed" nil t)
 (autoload 'kubed-create-cronjob "kubed" nil t)
 (autoload 'kubed-cronjob-prefix-map "kubed" nil t 'keymap)
 (autoload 'kubed-display-ingressclass "kubed" nil t)
 (autoload 'kubed-edit-ingressclass "kubed" nil t)
 (autoload 'kubed-delete-ingressclasses "kubed" nil t)
 (autoload 'kubed-list-ingressclasss "kubed" nil t)
 (autoload 'kubed-create-ingressclass "kubed" nil t)
 (autoload 'kubed-ingressclass-prefix-map "kubed" nil t 'keymap)
 (autoload 'kubed-display-ingress "kubed" nil t)
 (autoload 'kubed-edit-ingress "kubed" nil t)
 (autoload 'kubed-delete-ingresses "kubed" nil t)
 (autoload 'kubed-list-ingresss "kubed" nil t)
 (autoload 'kubed-create-ingress "kubed" nil t)
 (autoload 'kubed-ingress-prefix-map "kubed" nil t 'keymap)
(autoload 'kubed-use-context "kubed" "\
Set current Kubernetes context to CONTEXT.

(fn CONTEXT)" t)
(autoload 'kubed-rename-context "kubed" "\
Rename Kubernetes context OLD to NEW.

(fn OLD NEW)" t)
(autoload 'kubed-display-config "kubed" "\
Display current Kubernetes client settings in a YAML buffer." t)
(autoload 'kubed-set-namespace "kubed" "\
Set default Kubernetes namespace in CONTEXT to NAMESPACE.

Interactively, prompt for NAMESPACE and use the current context.  With a
prefix argument, prompt for CONTEXT as well.

(fn NAMESPACE &optional CONTEXT)" t)
(autoload 'kubed-apply "kubed" "\
Apply CONFIG to Kubernetes resource of kind KIND via CONTEXT.

(fn CONFIG &optional KIND CONTEXT)" t)
(autoload 'kubed-create "kubed" "\
Create resource of kind KIND with definition DEFINITION via CONTEXT.

(fn DEFINITION &optional KIND CONTEXT)" t)
(autoload 'kubed-run "kubed" "\
Run container IMAGE in a new Kubernetes POD.

Optional argument CONTEXT is the `kubectl' context to use, defaulting to
the current context.  NAMESPACE is the namespace in which to create POD,
defaulting to the current namespace.  PORT is the port to expose,
defaulting to none.  If ATTACH is non-nil, then attach to the created
image with a `comint-mode' buffer, and pop to that buffer.  Non-nil
STDIN says to keep the standard input of the container open; non-nil TTY
says to allocate a TTY for the container; and non-nil RM says to remove
the container after it exits.  ENVS is a list of strings \"VAR=VAL\"
which specify environment variables VAR and values VAL to give them in
the created container.  ARGS are command line arguments for the
container command.  If COMMAND is non-nil, ARGS consist of a complete
command line, that overrides the container command instead of just
providing it with arguments.

Interactively, prompt for POD and IMAGE.  With a prefix argument, prompt
for NAMESPACE; with a double prefix argument, also prompt for CONTEXT.

(fn POD IMAGE &optional CONTEXT NAMESPACE PORT ATTACH STDIN TTY RM ENVS COMMAND ARGS)" t)
(autoload 'kubed-logs "kubed" "\
Show logs for container CONTAINER in Kubernetes RESOURCE of type TYPE.

Optional argument CONTEXT is the `kubectl' context to use; NAMESPACE is
the namespace for RESOURCE; CONTAINER is the name of the container in
RESOURCE to show logs for, or t which specifies all relevant containers.

With a prefix argument, prompt for NAMESPACE; with a double prefix
argument, also prompt for CONTEXT.

(fn TYPE RESOURCE &optional CONTEXT NAMESPACE CONTAINER FOLLOW LIMIT PREFIX SINCE TAIL TIMESTAMPS)" t)
(autoload 'kubed-forward-port-to-pod "kubed" "\
Forward LOCAL-PORT to REMOTE-PORT of Kubernetes pod POD.

(fn POD LOCAL-PORT REMOTE-PORT CONTEXT NAMESPACE)" t)
(autoload 'kubed-attach "kubed" "\
Attach to running process in CONTAINER in Kubernetes POD.

Optional argument NAMESPACE is the namespace in which to look for POD.
Non-nil STDIN says to connect local standard input to remote process.
Non-nil TTY says to use a TTY for standard input.

Interactively, prompt for POD; if there are multiple pod containers,
prompt for CONTAINER as well.  With a prefix argument, prompt for
NAMESPACE too.  With a double prefix argument, also prompt for CONTEXT.
STDIN and TTY are t interactively.

(fn POD &optional CONTAINER CONTEXT NAMESPACE STDIN TTY)" t)
(autoload 'kubed-diff "kubed" "\
Display difference between Kubernetes resource DEFINITION and current state.

DEFINITION is either a file name or a buffer.  Interactively, prompt for
a YAML or JSON file name to use as DEFINITION.

Optional argument CONTEXT is the `kubectl' context to use, defaulting to
the current context; non-nil INCLUDE-MANAGED (interactively, the prefix
argument) says to include managed fields in the comparison.

(fn DEFINITION &optional INCLUDE-MANAGED CONTEXT)" t)
(autoload 'kubed-exec "kubed" "\
Execute COMMAND with ARGS in CONTAINER in Kubernetes POD.

Optional argument NAMESPACE is the namespace in which to look for POD.
Non-nil STDIN says to connect local standard input to remote process.
Non-nil TTY says to use a TTY for standard input.

Interactively, prompt for POD; if there are multiple pod containers,
prompt for CONTAINER as well.  With a prefix argument, prompt for
NAMESPACE too.  With a double prefix argument, also prompt for CONTEXT.
STDIN and TTY are t interactively.

(fn POD COMMAND &optional CONTAINER CONTEXT NAMESPACE STDIN TTY ARGS)" t)
(autoload 'kubed-patch "kubed" "\
Patch Kubernetes resource NAME of TYPE with patch PATCH.

Optional argument NAMESPACE is the namespace in which to look for NAME.
STRATEGY is the patch type to use, one of \"json\", \"merge\" and
\"strategic\", defaulting to \"strategic\".

Interactively, prompt for TYPE, NAME and PATCH.  With a prefix argument,
prompt for NAMESPACE too.  With a double prefix argument, also prompt
for CONTEXT.

(fn TYPE NAME PATCH &optional CONTEXT NAMESPACE STRATEGY)" t)
(autoload 'kubed-proxy "kubed" "\
Start a web server on localhost proxying the Kubernetes API server.

ADDR and PORT are the local address and port to bind the proxy server
to.  They default to 127.0.0.1 and 8001, respectively.  API-PREFIX is a
prefix under which to proxy the Kubernetes API.  WWW-DIR is a local
directory to serve under WWW-PREFIX, which defaults to \"/static/\".
Lastly, CONTEXT is the the `kubectl' context to use, defaulting to the
local context.

(fn &optional ADDR PORT API-PREFIX WWW-DIR WWW-PREFIX CONTEXT)" t)
(autoload 'kubed-stop-proxy "kubed" "\
Stop local proxy for context CONTEXT, defaulting to the local context.

(fn &optional CONTEXT)" t)
(autoload 'kubed-explain "kubed" "\
Show help buffer with explanation about Kubernetes resource FIELD.

(fn FIELD)" t)
(autoload 'kubed-kubectl-command "kubed" "\
Execute `kubectl' COMMAND.

This function calls `shell-command' (which see) to do the work.

Interactively, prompt for COMMAND with completion for `kubectl' arguments.

(fn COMMAND)" t)
 (autoload 'kubed-prefix-map "kubed" nil t 'keymap)
(defvar kubed-menu-bar-mode nil "\
Non-nil if Kubed-Menu-Bar mode is enabled.
See the `kubed-menu-bar-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `kubed-menu-bar-mode'.")
(custom-autoload 'kubed-menu-bar-mode "kubed" nil)
(autoload 'kubed-menu-bar-mode "kubed" "\
Add \"Kubernetes\" menu to your menu bar.

This is a global minor mode.  If called interactively, toggle the
`Kubed-Menu-Bar mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='kubed-menu-bar-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "kubed" '("kubed-"))


;;; Generated autoloads from kubed-common.el

(register-definition-prefixes "kubed-common" '("kubed-"))


;;; Generated autoloads from kubed-tramp.el

(autoload 'kubed-tramp-context "kubed-tramp" "\
Extract `kubectl' context from Kubed Tramp remote file name FILE-NAME.

(fn FILE-NAME)")
(autoload 'kubed-tramp-namespace "kubed-tramp" "\
Extract Kubernetes namespace from Kubed Tramp remote file name FILE-NAME.

(fn FILE-NAME)")
(autoload 'kubed-tramp-assert-support "kubed-tramp" "\
Check if Kubed Tramp support is available, throw `user-error' if not.")
(autoload 'kubed-tramp-enable "kubed-tramp" "\
Enable Kubed integration with Tramp.")
 (with-eval-after-load 'tramp (kubed-tramp-enable))
(register-definition-prefixes "kubed-tramp" '("kubed-tramp--"))


;;; Generated autoloads from kubed-transient.el

 (autoload 'kubed-transient "kubed-transient" nil t)
 (autoload 'kubed-transient-logs-for-pod "kubed-transient" nil t)
 (autoload 'kubed-transient-logs-for-deployment "kubed-transient" nil t)
 (autoload 'kubed-transient-logs-for-service "kubed-transient" nil t)
 (autoload 'kubed-transient-logs-for-job "kubed-transient" nil t)
 (autoload 'kubed-transient-logs-for-replicaset "kubed-transient" nil t)
 (autoload 'kubed-transient-logs-for-daemonset "kubed-transient" nil t)
 (autoload 'kubed-transient-logs-for-statefulset "kubed-transient" nil t)
 (autoload 'kubed-transient-logs "kubed-transient" nil t)
 (autoload 'kubed-transient-scale-deployment "kubed-transient" nil t)
 (autoload 'kubed-transient-proxy "kubed-transient" nil t)
 (autoload 'kubed-transient-rollout "kubed-transient" nil t)
 (autoload 'kubed-transient-attach "kubed-transient" nil t)
 (autoload 'kubed-transient-diff "kubed-transient" nil t)
 (autoload 'kubed-transient-exec "kubed-transient" nil t)
 (autoload 'kubed-transient-run "kubed-transient" nil t)
 (autoload 'kubed-transient-apply "kubed-transient" nil t)
 (autoload 'kubed-transient-patch "kubed-transient" nil t)
 (autoload 'kubed-transient-create "kubed-transient" nil t)
 (autoload 'kubed-transient-display "kubed-transient" nil t)
 (autoload 'kubed-transient-edit "kubed-transient" nil t)
 (autoload 'kubed-transient-delete "kubed-transient" nil t)
 (autoload 'kubed-transient-create-cronjob "kubed-transient" nil t)
 (autoload 'kubed-transient-create-ingress "kubed-transient" nil t)
 (autoload 'kubed-transient-create-deployment "kubed-transient" nil t)
 (autoload 'kubed-transient-create-job "kubed-transient" nil t)
 (autoload 'kubed-list-transient "kubed-transient" nil t)
(register-definition-prefixes "kubed-transient" '("kubed-transient-"))

;;; End of scraped data

(provide 'kubed-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; kubed-autoloads.el ends here
