;;; ejc-sql-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ejc-autocomplete.el

(autoload 'ejc-ac-setup "ejc-autocomplete" "\
Add the completion sources to the front of `ac-sources'.
This affects only the current buffer.

Check against following cases:
prefix-2.prefix-1.#
prefix-1.#
something#" t)
(register-definition-prefixes "ejc-autocomplete" '("ac-source-ejc-" "ejc-ac-hook"))


;;; Generated autoloads from ejc-company.el

(register-definition-prefixes "ejc-company" '("ejc-company-"))


;;; Generated autoloads from ejc-completion-common.el

(autoload 'ejc-owners-candidates "ejc-completion-common")
(autoload 'ejc-tables-candidates "ejc-completion-common")
(autoload 'ejc-views-candidates "ejc-completion-common")
(autoload 'ejc-packages-candidates "ejc-completion-common")
(autoload 'ejc-colomns-candidates "ejc-completion-common")
(register-definition-prefixes "ejc-completion-common" '("ac-ejc-documentation" "ejc-"))


;;; Generated autoloads from ejc-doc.el

(register-definition-prefixes "ejc-doc" '("ejc-"))


;;; Generated autoloads from ejc-eldoc.el

(autoload 'ejc-eldoc-setup "ejc-eldoc" "\
Set up eldoc function and enable eldoc-mode." t)
(register-definition-prefixes "ejc-eldoc" '("ejc-"))


;;; Generated autoloads from ejc-flx.el

(register-definition-prefixes "ejc-flx" '("ejc-"))


;;; Generated autoloads from ejc-format.el

(register-definition-prefixes "ejc-format" '("ejc-"))


;;; Generated autoloads from ejc-interaction.el

(register-definition-prefixes "ejc-interaction" '("ejc-"))


;;; Generated autoloads from ejc-lib.el

(register-definition-prefixes "ejc-lib" '("ejc-"))


;;; Generated autoloads from ejc-result-buffer.el

(autoload 'ejc-show-last-result "ejc-result-buffer" "\
Popup buffer with last SQL execution result output.

(fn &key RESULT MODE CONNECTION-NAME DB GOTO-SYMBOL)" t)
(autoload 'ejc-show-prev-result "ejc-result-buffer" "\
Change `ejc-results-buffer' contents: show previous SQL evaluation result." t)
(autoload 'ejc-show-next-result "ejc-result-buffer" "\
Change `ejc-results-buffer' contents: show next SQL evaluation result." t)
(register-definition-prefixes "ejc-result-buffer" '("ejc-"))


;;; Generated autoloads from ejc-result-mode.el

(register-definition-prefixes "ejc-result-mode" '("ejc-result-"))


;;; Generated autoloads from ejc-sql.el

(autoload 'ejc-sql-mode "ejc-sql" "\
Toggle ejc-sql mode.

This is a minor mode.  If called interactively, toggle the `ejc-Sql
mode' mode.  If the prefix argument is positive, enable the mode, and if
it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `ejc-sql-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'ejc-create-menu "ejc-sql")
(autoload 'ejc-insert-connection-data "ejc-sql" "\
Insert configured connection data to keep it between Emacs restarts.
Assume to be evaluated somewhere in .emacs or any file, loaded as Emacs
configuration.

(fn CONNECTION-NAME)" t)
(autoload 'ejc-connect-interactive "ejc-sql" "\
Create new connection interactively and connect to it.

(fn CONNECTION-NAME)" t)
(autoload 'ejc-connect "ejc-sql" "\
Connect to selected db.

(fn CONNECTION-NAME)" t)
(autoload 'ejc-connect-existing-repl "ejc-sql" "\
Connect to existing ejc-sql nREPL running process.
You can `cd` to your ejc-sql project folder (typically
'~/.emacs.d/elpa/ejc-sql-<version>') and launch nREPL via `lein repl`.
Then run in Emacs `ejc-connect-existing-repl', type HOST and PORT
from your `lein run` console output. Finally, use `ejc-connect' from
any SQL buffer to connect to exact database, as always. " t)
(autoload 'ejc-eval-user-sql-region "ejc-sql" "\
Evaluate SQL bounded by the selection area.

(fn BEG END)" t)
(autoload 'ejc-eval-user-sql-at-point "ejc-sql" "\
Evaluate SQL bounded by the `ejc-sql-separator' or/and buffer
boundaries.

(fn &key SYNC BEG END (DISPLAY-RESULT t))" t)
(autoload 'ejc-show-tables-list "ejc-sql" "\
Output tables list." t)
(autoload 'ejc-show-views-list "ejc-sql" "\
Output views list." t)
(autoload 'ejc-show-user-types-list "ejc-sql" "\
Output user types list.

(fn &optional OWNER)" t)
(autoload 'ejc-show-constraints-list "ejc-sql" "\
Output constraints list.

(fn &optional OWNER TABLE)" t)
(autoload 'ejc-show-procedures-list "ejc-sql" "\
Output procedures list." t)
(autoload 'ejc-get-temp-editor-buffer "ejc-sql" "\


(fn &optional NUM)" t)
(autoload 'ejc-version "ejc-sql" "\
Get the ejc-sql version as string." t)
(register-definition-prefixes "ejc-sql" '("ejc-"))

;;; End of scraped data

(provide 'ejc-sql-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ejc-sql-autoloads.el ends here
