;;; flymake-perlcritic-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from flymake-perlcritic.el

(autoload 'flymake-perlcritic-setup "flymake-perlcritic" "\
Set up Flymake perlcritic.
Add perlcritic to the Flymake diagnostic functions.  To use it,
add this function to `perl-mode-hook'.")
(register-definition-prefixes "flymake-perlcritic" '("flymake-perlcritic-"))

;;; End of scraped data

(provide 'flymake-perlcritic-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; flymake-perlcritic-autoloads.el ends here
