;;; mvn-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from mvn.el

(autoload 'mvn-kill-cache "mvn" nil t)
(autoload 'mvn "mvn" "\
Run mvn `task` in project root directory.

(fn &optional TASK ARGS)" t)
(autoload 'mvn-last "mvn" "\
Run the last maven task in project" t)
(autoload 'mvn-compile "mvn" nil t)
(autoload 'mvn-clean "mvn" nil t)
(autoload 'mvn-test "mvn" "\


(fn PREFIX)" t)
(register-definition-prefixes "mvn" '("mvn-"))

;;; End of scraped data

(provide 'mvn-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; mvn-autoloads.el ends here
