;;; soap-client-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from soap-client.el

(register-definition-prefixes "soap-client" '("soap-"))


;;; Generated autoloads from soap-inspect.el

(register-definition-prefixes "soap-inspect" '("soap-"))

;;; End of scraped data

(provide 'soap-client-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; soap-client-autoloads.el ends here
