;;; kubel-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from kubel.el

(autoload 'kubel-yaml-editing-mode "kubel" "\
Kubel Yaml editing mode.

Allows simple apply of the changes made.

\\{kubel-yaml-editing-mode-map}

(fn)" t)
(autoload 'kubel-vterm-setup "kubel" "\
Adds a vterm enty to the KUBEL-EXEC-POP.")
(autoload 'kubel-refresh "kubel" "\
Refresh the current kubel buffer, calling kubectl using the configured
context, namespace, and resource.

DIRECTORY is optional for TRAMP support.

(fn &optional DIRECTORY)" t)
(autoload 'kubel-open "kubel" "\
Create a new kubel buffer using passed parameters CONTEXT NAMESPACE RESOURCE.
DIRECTORY is optional for TRAMP support.

(fn CONTEXT NAMESPACE RESOURCE &optional DIRECTORY)")
(autoload 'kubel "kubel" "\
Invoke the kubel buffer.
DIRECTORY is optional for TRAMP support.

(fn &optional DIRECTORY)" t)
(register-definition-prefixes "kubel" '("kubel-"))

;;; End of scraped data

(provide 'kubel-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; kubel-autoloads.el ends here
