 (deftheme bba1 "DOCSTRING for bba1")
   (custom-theme-set-faces 'bba1
    '(default ((default (:foreground "#07e30d" :background "#000000" ))))
    '(cursor ((default (:background "#f09213" ))))
    '(fringe ((default (:background "#131313" ))))
    '(mode-line ((default (:foreground "#282828" :background "#d96503" ))))
    '(region ((default (:background "#7a7674" ))))
    '(secondary-selection ((default (:background "#584e47" ))))
    '(font-lock-builtin-face ((default (:foreground "#fe8019" ))))
    '(font-lock-comment-face ((default (:foreground "#df7114" ))))
    '(font-lock-function-name-face ((default (:foreground "#b8bb26" ))))
    '(font-lock-keyword-face ((default (:foreground "#fb4934" ))))
    '(font-lock-string-face ((default (:foreground "#b8bb26" ))))
    '(font-lock-type-face ((default (:foreground "#d3869b" ))))
    '(font-lock-constant-face ((default (:foreground "#d3869b" ))))
    '(font-lock-variable-name-face ((default (:foreground "#83a598" ))))
    '(minibuffer-prompt ((default (:foreground "#b8bb26" :bold t ))))
    '(font-lock-warning-face ((default (:foreground "red" :bold t ))))
    )
 (provide-theme 'bba1)

