;;; org-chef-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from org-chef.el

(autoload 'org-chef-insert-recipe "org-chef" "\
Prompt for a recipe URL, and then insert the recipe at point.

(fn URL)" t)
(autoload 'org-chef-get-recipe-from-url "org-chef" "\
Prompt for a recipe URL, and return the ‘org-mode’ string.")
(register-definition-prefixes "org-chef" '("org-chef-"))


;;; Generated autoloads from org-chef-24kitchen.el

(register-definition-prefixes "org-chef-24kitchen" '("org-chef-24kitchen-"))


;;; Generated autoloads from org-chef-basics-with-babish.el

(register-definition-prefixes "org-chef-basics-with-babish" '("org-chef-basics-with-babish-"))


;;; Generated autoloads from org-chef-bbc-food.el

(register-definition-prefixes "org-chef-bbc-food" '("org-chef-bbc-food-"))


;;; Generated autoloads from org-chef-bbc-good-food.el

(register-definition-prefixes "org-chef-bbc-good-food" '("org-chef-bbc-good-food-"))


;;; Generated autoloads from org-chef-binging-with-babish.el

(register-definition-prefixes "org-chef-binging-with-babish" '("org-chef-b"))


;;; Generated autoloads from org-chef-chef-koch.el

(register-definition-prefixes "org-chef-chef-koch" '("org-chef-chef-koch-"))


;;; Generated autoloads from org-chef-cultures-for-health.el

(register-definition-prefixes "org-chef-cultures-for-health" '("org-chef-cultures-for-health-"))


;;; Generated autoloads from org-chef-edit.el

(autoload 'org-chef-edit-servings "org-chef-edit" "\
Changes the serving count of an org-chef recipe entry to DESIRED, also modifying
the quantities inside the ingredients list.

(fn DESIRED)" t)
(register-definition-prefixes "org-chef-edit" '("org-chef-edit--"))


;;; Generated autoloads from org-chef-fine-cooking.el

(register-definition-prefixes "org-chef-fine-cooking" '("org-chef-fine-cooking-"))


;;; Generated autoloads from org-chef-genius-kitchen.el

(register-definition-prefixes "org-chef-genius-kitchen" '("org-chef-genius-kitchen-"))


;;; Generated autoloads from org-chef-jamie-oliver.el

(register-definition-prefixes "org-chef-jamie-oliver" '("org-chef-jamie-oliver-"))


;;; Generated autoloads from org-chef-json-ld.el

(register-definition-prefixes "org-chef-json-ld" '("org-chef-json-ld-"))


;;; Generated autoloads from org-chef-kotikokki.el

(register-definition-prefixes "org-chef-kotikokki" '("org-chef-kotikokki-"))


;;; Generated autoloads from org-chef-marmiton.el

(register-definition-prefixes "org-chef-marmiton" '("org-chef-marmiton-"))


;;; Generated autoloads from org-chef-martha-stewart.el

(register-definition-prefixes "org-chef-martha-stewart" '("org-chef-martha-stewart-"))


;;; Generated autoloads from org-chef-nytimes.el

(register-definition-prefixes "org-chef-nytimes" '("org-chef-nytimes-"))


;;; Generated autoloads from org-chef-recipetin-eats.el

(register-definition-prefixes "org-chef-recipetin-eats" '("org-chef-recipetin-eats-"))


;;; Generated autoloads from org-chef-reluctant-gourmet.el

(register-definition-prefixes "org-chef-reluctant-gourmet" '("org-chef-reluctant-gourmet-"))


;;; Generated autoloads from org-chef-saveur.el

(register-definition-prefixes "org-chef-saveur" '("org-chef-saveur-"))


;;; Generated autoloads from org-chef-serious-eats.el

(register-definition-prefixes "org-chef-serious-eats" '("org-chef-serious-eats-"))


;;; Generated autoloads from org-chef-simply-recipes.el

(register-definition-prefixes "org-chef-simply-recipes" '("org-chef-simply-recipes-"))


;;; Generated autoloads from org-chef-taste.el

(register-definition-prefixes "org-chef-taste" '("org-chef-taste-"))


;;; Generated autoloads from org-chef-utils.el

(register-definition-prefixes "org-chef-utils" '("org-chef-"))


;;; Generated autoloads from org-chef-wordpress.el

(register-definition-prefixes "org-chef-wordpress" '("org-chef-"))


;;; Generated autoloads from org-chef-xiachufang.el

(register-definition-prefixes "org-chef-xiachufang" '("org-chef-xiachufang-"))

;;; End of scraped data

(provide 'org-chef-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; org-chef-autoloads.el ends here
