;;; kubedoc-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from kubedoc.el

(autoload 'kubedoc "kubedoc" "\
Show Kubernetes API documentation.
Uses current context." t)
(autoload 'kubedoc-for-context "kubedoc" "\
Show Kubernetes API documentation.
Prompts for changing current context." t)
(register-definition-prefixes "kubedoc" '("kubedoc-"))

;;; End of scraped data

(provide 'kubedoc-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; kubedoc-autoloads.el ends here
