;;; kubel-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from kubel.el

(autoload 'kubel-yaml-editing-mode "kubel" "\
Kubel Yaml editing mode.

Use C-c C-c to kubectl apply the current yaml buffer.

This is a minor mode.  If called interactively, toggle the
`Kubel-Yaml-Editing mode' mode.  If the prefix argument is
positive, enable the mode, and if it is zero or negative, disable
the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `kubel-yaml-editing-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(autoload 'kubel-vterm-setup "kubel" "\
Adds a vterm enty to the KUBEL-EXEC-POP.")
(autoload 'kubel-refresh "kubel" "\
Refresh the current kubel buffer, calling kubectl using the configured
context, namespace, and resource.

DIRECTORY is optional for TRAMP support.

(fn &optional DIRECTORY)" t)
(autoload 'kubel-open "kubel" "\
Create a new kubel buffer using passed parameters CONTEXT NAMESPACE RESOURCE.
DIRECTORY is optional for TRAMP support.

(fn CONTEXT NAMESPACE RESOURCE &optional DIRECTORY)")
(autoload 'kubel "kubel" "\
Invoke the kubel buffer.
DIRECTORY is optional for TRAMP support.

(fn &optional DIRECTORY)" t)
(register-definition-prefixes "kubel" '("kubel-"))

;;; End of scraped data

(provide 'kubel-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; kubel-autoloads.el ends here
