;;; yaml-pro-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from yaml-pro.el

(autoload 'yaml-pro-ts-mode "yaml-pro" "\
Minor mode to enable yaml-pro treesitter keymap.

\\{yaml-pro-mode-map}

This is a minor mode.  If called interactively, toggle the `Yaml-Pro-Ts
mode' mode.  If the prefix argument is positive, enable the mode, and if
it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `yaml-pro-ts-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'yaml-pro-mode "yaml-pro" "\
Binds additional functions to aid in editing YAML files.

\\{yaml-pro-mode-map}

This is a minor mode.  If called interactively, toggle the `Yaml-Pro
mode' mode.  If the prefix argument is positive, enable the mode, and if
it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `yaml-pro-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "yaml-pro" '("yaml-pro-"))


;;; Generated autoloads from yaml-pro-edit.el

(autoload 'yaml-pro-edit-scalar "yaml-pro-edit" "\
Edit the scalar value at the point in a separate buffer.
If prefix argument P is provided, prompt user for initialization command.

(fn P)" t)
(register-definition-prefixes "yaml-pro-edit" '("yaml-pro-edit-"))


;;; Generated autoloads from yaml-pro-format.el

(register-definition-prefixes "yaml-pro-format" '("yaml-pro-format"))

;;; End of scraped data

(provide 'yaml-pro-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; yaml-pro-autoloads.el ends here
