;;; mew-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from mew.el

(autoload 'mew "mew" "\
Execute Mew first unless Mew is running. And retrieve arrived
messages or just visit to the default folder.

`proto' is determined by `mew-proto' and `mew-case'.

If `proto' is `+' (ie a local folder), a mailbox is determined
according to `mew-mailbox-type'. Otherwise (ie a remote folder), an
appropriate protocol to retrieve messages is chosen according to
`proto'.

If `mew-auto-get' is `t', arrived messages are asynchronously fetched
and listed up in Summary mode.

`mew-auto-get' is `nil', just visit to the folder determined by
`proto'.

When executed with `\\[universal-argument]', `mew-auto-get' is
considered reversed.

(fn &optional ARG)" t)
(autoload 'mew-send "mew" "\
Execute Mew then prepare a draft. This may be used as library
function.

(fn &optional TO CC SUBJECT)" t)
(autoload 'mew-user-agent-compose "mew" "\
Set up message composition draft with Mew.
This is `mail-user-agent' entry point to Mew.

The optional arguments TO and SUBJECT specify recipients and the
initial Subject field, respectively.

OTHER-HEADERS is an alist specifying additional
header fields.  Elements look like (HEADER . VALUE) where both
HEADER and VALUE are strings.

A Draft buffer is prepared according to SWITCH-FUNCTION.

CONTINUE, YANK-ACTION and SEND-ACTIONS are ignored.

(fn &optional TO SUBJECT OTHER-HEADERS CONTINUE SWITCH-FUNCTION YANK-ACTION SEND-ACTIONS &rest DUMMY)")
(register-definition-prefixes "mew" '("mew-"))


;;; Generated autoloads from mew-addrbook.el

(register-definition-prefixes "mew-addrbook" '("mew-"))


;;; Generated autoloads from mew-attach.el

(register-definition-prefixes "mew-attach" '("mew-"))


;;; Generated autoloads from mew-auth.el

(register-definition-prefixes "mew-auth" '("mew-"))


;;; Generated autoloads from mew-blvs.el

(register-definition-prefixes "mew-blvs" '("mew-"))


;;; Generated autoloads from mew-bq.el

(register-definition-prefixes "mew-bq" '("mew-"))


;;; Generated autoloads from mew-cache.el

(register-definition-prefixes "mew-cache" '("mew-"))


;;; Generated autoloads from mew-complete.el

(register-definition-prefixes "mew-complete" '("mew-"))


;;; Generated autoloads from mew-config.el

(register-definition-prefixes "mew-config" '("mew-"))


;;; Generated autoloads from mew-const.el

(register-definition-prefixes "mew-const" '("mew-"))


;;; Generated autoloads from mew-darwin.el

(register-definition-prefixes "mew-darwin" '("mew-"))


;;; Generated autoloads from mew-decode.el

(register-definition-prefixes "mew-decode" '("mew-"))


;;; Generated autoloads from mew-demo.el

(register-definition-prefixes "mew-demo" '("mew-"))


;;; Generated autoloads from mew-draft.el

(register-definition-prefixes "mew-draft" '("mew-"))


;;; Generated autoloads from mew-edit.el

(register-definition-prefixes "mew-edit" '("mew-"))


;;; Generated autoloads from mew-encode.el

(register-definition-prefixes "mew-encode" '("mew-"))


;;; Generated autoloads from mew-env.el

(register-definition-prefixes "mew-env" '("mew-"))


;;; Generated autoloads from mew-env0.el

(register-definition-prefixes "mew-env0" '("mew-no-warning-def"))


;;; Generated autoloads from mew-exec.el

(register-definition-prefixes "mew-exec" '("mew-"))


;;; Generated autoloads from mew-ext.el

(register-definition-prefixes "mew-ext" '("mew-"))


;;; Generated autoloads from mew-fib.el

(register-definition-prefixes "mew-fib" '("mew-fib-"))


;;; Generated autoloads from mew-func.el

(register-definition-prefixes "mew-func" '("mew-"))


;;; Generated autoloads from mew-gemacs.el

(register-definition-prefixes "mew-gemacs" '("mew-"))


;;; Generated autoloads from mew-header.el

(register-definition-prefixes "mew-header" '("mew-"))


;;; Generated autoloads from mew-highlight.el

(register-definition-prefixes "mew-highlight" '("mew-"))


;;; Generated autoloads from mew-imap.el

(register-definition-prefixes "mew-imap" '("mew-"))


;;; Generated autoloads from mew-imap2.el

(register-definition-prefixes "mew-imap2" '("mew-"))


;;; Generated autoloads from mew-key.el

(register-definition-prefixes "mew-key" '("mew-"))


;;; Generated autoloads from mew-lang-jp.el

(register-definition-prefixes "mew-lang-jp" '("mew-"))


;;; Generated autoloads from mew-lang-kr.el

(register-definition-prefixes "mew-lang-kr" '("mew-thread-indent-strings"))


;;; Generated autoloads from mew-lang-latin.el

(register-definition-prefixes "mew-lang-latin" '("mew-"))


;;; Generated autoloads from mew-local.el

(register-definition-prefixes "mew-local" '("mew-"))


;;; Generated autoloads from mew-mark.el

(register-definition-prefixes "mew-mark" '("mew-"))


;;; Generated autoloads from mew-message.el

(register-definition-prefixes "mew-message" '("mew-"))


;;; Generated autoloads from mew-mime.el

(register-definition-prefixes "mew-mime" '("mew-"))


;;; Generated autoloads from mew-minibuf.el

(register-definition-prefixes "mew-minibuf" '("mew-"))


;;; Generated autoloads from mew-mule.el

(register-definition-prefixes "mew-mule" '("mew-"))


;;; Generated autoloads from mew-mule3.el

(register-definition-prefixes "mew-mule3" '("mew-"))


;;; Generated autoloads from mew-net.el

(register-definition-prefixes "mew-net" '("mew-"))


;;; Generated autoloads from mew-nntp.el

(register-definition-prefixes "mew-nntp" '("mew-"))


;;; Generated autoloads from mew-nntp2.el

(register-definition-prefixes "mew-nntp2" '("mew-nntp2-"))


;;; Generated autoloads from mew-oauth2.el

(register-definition-prefixes "mew-oauth2" '("mew-"))


;;; Generated autoloads from mew-passwd.el

(register-definition-prefixes "mew-passwd" '("mew-"))


;;; Generated autoloads from mew-pgp.el

(register-definition-prefixes "mew-pgp" '("mew-"))


;;; Generated autoloads from mew-pick.el

(register-definition-prefixes "mew-pick" '("mew-"))


;;; Generated autoloads from mew-pop.el

(register-definition-prefixes "mew-pop" '("mew-"))


;;; Generated autoloads from mew-refile.el

(register-definition-prefixes "mew-refile" '("mew-"))


;;; Generated autoloads from mew-scan.el

(register-definition-prefixes "mew-scan" '("mew-"))


;;; Generated autoloads from mew-search.el

(register-definition-prefixes "mew-search" '("mew-"))


;;; Generated autoloads from mew-smime.el

(register-definition-prefixes "mew-smime" '("mew-"))


;;; Generated autoloads from mew-smtp.el

(register-definition-prefixes "mew-smtp" '("mew-"))


;;; Generated autoloads from mew-sort.el

(register-definition-prefixes "mew-sort" '("mew-s"))


;;; Generated autoloads from mew-ssh.el

(register-definition-prefixes "mew-ssh" '("mew-"))


;;; Generated autoloads from mew-ssl.el

(register-definition-prefixes "mew-ssl" '("mew-"))


;;; Generated autoloads from mew-summary.el

(register-definition-prefixes "mew-summary" '("mew-"))


;;; Generated autoloads from mew-summary2.el

(register-definition-prefixes "mew-summary2" '("mew-"))


;;; Generated autoloads from mew-summary3.el

(register-definition-prefixes "mew-summary3" '("mew-"))


;;; Generated autoloads from mew-summary4.el

(register-definition-prefixes "mew-summary4" '("mew-"))


;;; Generated autoloads from mew-syntax.el

(register-definition-prefixes "mew-syntax" '("mew-"))


;;; Generated autoloads from mew-thread.el

(register-definition-prefixes "mew-thread" '("mew-"))


;;; Generated autoloads from mew-unix.el

(register-definition-prefixes "mew-unix" '("mew-"))


;;; Generated autoloads from mew-vars.el

(register-definition-prefixes "mew-vars" '("mew-"))


;;; Generated autoloads from mew-vars2.el

(register-definition-prefixes "mew-vars2" '("mew-"))


;;; Generated autoloads from mew-vars3.el

(register-definition-prefixes "mew-vars3" '("mew-"))


;;; Generated autoloads from mew-varsx.el

(register-definition-prefixes "mew-varsx" '("mew-defvar"))


;;; Generated autoloads from mew-virtual.el

(register-definition-prefixes "mew-virtual" '("mew-"))


;;; Generated autoloads from mew-win32.el

(register-definition-prefixes "mew-win32" '("mew-"))

;;; End of scraped data

(provide 'mew-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; mew-autoloads.el ends here
